accueil.render:
  path: '/accueil'
  controller: '\Core\controller\accueil::accueil'
  title: 'Marmiton'

newRecette.render:
  path: '/recette/add'
  controller: '\Core\controller\form::recetteForm'
  title: 'Marmiton'