accueil.render:
  path: '/accueil'
  controller: '\Core\controller\accueil::accueil'
  title: 'Marmiton'

newRecette.render:
  path: '/recette/add'
  controller: '\Core\controller\form::recetteForm'
  title: 'Marmiton'
  
renderRecette.render:
  path: '/recette'
  controller: '\Core\controller\recettec::renderRecette'
  title: 'Marmiton'
  
test.render:
  path: '/test'
  controller: '\Core\controller\accueil::test'
  title: 'Marmiton'
  
resultat.render:
  path: '/resultat'
  controller: '\Core\controller\accueil::resultat'
  title: 'Marmiton'
  
recherche.render:
  path: '/recherche'
  controller: '\Core\controller\accueil::recherche'
  title: 'Marmiton'